### ISSUE TITLE
Parsing Error

### ISSUE THREAD

**Issue by mayhemdevel** [discord/linked-roles-sample#25]
![image](https://github.com/discord/linked-roles-sample/assets/105621089/3d01467e-e229-4172-90eb-70e1cc31a4e6)

**Comment by mayhemdevel** [comment]
![image](https://github.com/discord/linked-roles-sample/assets/105621089/99de96ee-b593-4e12-b237-70ad14dfc61d)

**Comment by JustinBeckwith** [comment]
Greetings!  This means you're very likely running an old version of node.  What's the output of this?

```
node -v
```

I would suggest upgrading to node 20 and giving it another go.
